// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ecountgmifs_call_score_criterion
double ecountgmifs_call_score_criterion(SEXP criterion, uint64_t iteration, double negloglik, double unpenalized_negloglik, double saturated_negloglik, double n, double p, double nnz, double df, double active_size, double dispersion, double enet_norm, double epsilon);
RcppExport SEXP _ecountgmifs_ecountgmifs_call_score_criterion(SEXP criterionSEXP, SEXP iterationSEXP, SEXP negloglikSEXP, SEXP unpenalized_negloglikSEXP, SEXP saturated_negloglikSEXP, SEXP nSEXP, SEXP pSEXP, SEXP nnzSEXP, SEXP dfSEXP, SEXP active_sizeSEXP, SEXP dispersionSEXP, SEXP enet_normSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type criterion(criterionSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< double >::type negloglik(negloglikSEXP);
    Rcpp::traits::input_parameter< double >::type unpenalized_negloglik(unpenalized_negloglikSEXP);
    Rcpp::traits::input_parameter< double >::type saturated_negloglik(saturated_negloglikSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nnz(nnzSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type active_size(active_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type enet_norm(enet_normSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(ecountgmifs_call_score_criterion(criterion, iteration, negloglik, unpenalized_negloglik, saturated_negloglik, n, p, nnz, df, active_size, dispersion, enet_norm, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// ecountgmifs_cpp
Rcpp::List ecountgmifs_cpp(arma::mat X, arma::vec y, arma::mat w, arma::vec offset, arma::vec yorig, arma::mat Xtest, arma::vec ytest, arma::mat wtest, arma::vec offsettest, const arma::vec& weight_vec, double enet_alpha, double epsilon_start, double epsilon_max, double epsilon_min_tol, double tol, uint32_t iteration_max, uint32_t family, uint32_t linkfunc_int, double nlopt_optim_reltol, double loglik_reltol_cutoff, bool verbose, bool is_fixed_disp, double fixed_disp_value, int state_track_strategy, uint64_t state_track_freq, Rcpp::Nullable<Rcpp::List> criteria);
RcppExport SEXP _ecountgmifs_ecountgmifs_cpp(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP offsetSEXP, SEXP yorigSEXP, SEXP XtestSEXP, SEXP ytestSEXP, SEXP wtestSEXP, SEXP offsettestSEXP, SEXP weight_vecSEXP, SEXP enet_alphaSEXP, SEXP epsilon_startSEXP, SEXP epsilon_maxSEXP, SEXP epsilon_min_tolSEXP, SEXP tolSEXP, SEXP iteration_maxSEXP, SEXP familySEXP, SEXP linkfunc_intSEXP, SEXP nlopt_optim_reltolSEXP, SEXP loglik_reltol_cutoffSEXP, SEXP verboseSEXP, SEXP is_fixed_dispSEXP, SEXP fixed_disp_valueSEXP, SEXP state_track_strategySEXP, SEXP state_track_freqSEXP, SEXP criteriaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yorig(yorigSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytest(ytestSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wtest(wtestSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offsettest(offsettestSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< double >::type enet_alpha(enet_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_start(epsilon_startSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_max(epsilon_maxSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_min_tol(epsilon_min_tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type iteration_max(iteration_maxSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type family(familySEXP);
    Rcpp::traits::input_parameter< uint32_t >::type linkfunc_int(linkfunc_intSEXP);
    Rcpp::traits::input_parameter< double >::type nlopt_optim_reltol(nlopt_optim_reltolSEXP);
    Rcpp::traits::input_parameter< double >::type loglik_reltol_cutoff(loglik_reltol_cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type is_fixed_disp(is_fixed_dispSEXP);
    Rcpp::traits::input_parameter< double >::type fixed_disp_value(fixed_disp_valueSEXP);
    Rcpp::traits::input_parameter< int >::type state_track_strategy(state_track_strategySEXP);
    Rcpp::traits::input_parameter< uint64_t >::type state_track_freq(state_track_freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type criteria(criteriaSEXP);
    rcpp_result_gen = Rcpp::wrap(ecountgmifs_cpp(X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, linkfunc_int, nlopt_optim_reltol, loglik_reltol_cutoff, verbose, is_fixed_disp, fixed_disp_value, state_track_strategy, state_track_freq, criteria));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecountgmifs_ecountgmifs_call_score_criterion", (DL_FUNC) &_ecountgmifs_ecountgmifs_call_score_criterion, 13},
    {"_ecountgmifs_ecountgmifs_cpp", (DL_FUNC) &_ecountgmifs_ecountgmifs_cpp, 26},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecountgmifs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
