// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ecountgmifs_call_context_criterion
double ecountgmifs_call_context_criterion(SEXP criterion_ptr, double negloglik, uint64_t iteration, double dispersion, double epsilon, bool initialized, double n, double p, double q, double beta_value, double beta_nonzero_value, uint64_t nnz, double enet_alpha, bool include_data);
RcppExport SEXP _ecountgmifs_ecountgmifs_call_context_criterion(SEXP criterion_ptrSEXP, SEXP negloglikSEXP, SEXP iterationSEXP, SEXP dispersionSEXP, SEXP epsilonSEXP, SEXP initializedSEXP, SEXP nSEXP, SEXP pSEXP, SEXP qSEXP, SEXP beta_valueSEXP, SEXP beta_nonzero_valueSEXP, SEXP nnzSEXP, SEXP enet_alphaSEXP, SEXP include_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type criterion_ptr(criterion_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type negloglik(negloglikSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type initialized(initializedSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type beta_value(beta_valueSEXP);
    Rcpp::traits::input_parameter< double >::type beta_nonzero_value(beta_nonzero_valueSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type nnz(nnzSEXP);
    Rcpp::traits::input_parameter< double >::type enet_alpha(enet_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type include_data(include_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(ecountgmifs_call_context_criterion(criterion_ptr, negloglik, iteration, dispersion, epsilon, initialized, n, p, q, beta_value, beta_nonzero_value, nnz, enet_alpha, include_data));
    return rcpp_result_gen;
END_RCPP
}
// ecountgmifs_cpp
Rcpp::List ecountgmifs_cpp(arma::mat X, arma::vec y, arma::mat w, arma::vec offset, arma::vec yorig, arma::mat Xtest, arma::vec ytest, arma::mat wtest, arma::vec offsettest, const arma::vec& weight_vec, double enet_alpha, double epsilon_start, double epsilon_max, double epsilon_min_tol, double tol, uint32_t iteration_max, SEXP family, SEXP link_func, Rcpp::Nullable<Rcpp::List> criteria, double loglik_reltol_cutoff, double enet_abs_tol, double enet_rel_tol, uint32_t enet_max_iter, bool verbose, bool include_data, int state_track_strategy, uint64_t state_track_freq, const arma::vec& theta_initial, const arma::vec& theta_lower_bounds, const arma::vec& theta_upper_bounds, int nlopt_algorithm, double nlopt_xtol_rel, double nlopt_ftol_rel, int nlopt_maxeval);
RcppExport SEXP _ecountgmifs_ecountgmifs_cpp(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP offsetSEXP, SEXP yorigSEXP, SEXP XtestSEXP, SEXP ytestSEXP, SEXP wtestSEXP, SEXP offsettestSEXP, SEXP weight_vecSEXP, SEXP enet_alphaSEXP, SEXP epsilon_startSEXP, SEXP epsilon_maxSEXP, SEXP epsilon_min_tolSEXP, SEXP tolSEXP, SEXP iteration_maxSEXP, SEXP familySEXP, SEXP link_funcSEXP, SEXP criteriaSEXP, SEXP loglik_reltol_cutoffSEXP, SEXP enet_abs_tolSEXP, SEXP enet_rel_tolSEXP, SEXP enet_max_iterSEXP, SEXP verboseSEXP, SEXP include_dataSEXP, SEXP state_track_strategySEXP, SEXP state_track_freqSEXP, SEXP theta_initialSEXP, SEXP theta_lower_boundsSEXP, SEXP theta_upper_boundsSEXP, SEXP nlopt_algorithmSEXP, SEXP nlopt_xtol_relSEXP, SEXP nlopt_ftol_relSEXP, SEXP nlopt_maxevalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yorig(yorigSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ytest(ytestSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wtest(wtestSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offsettest(offsettestSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< double >::type enet_alpha(enet_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_start(epsilon_startSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_max(epsilon_maxSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_min_tol(epsilon_min_tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type iteration_max(iteration_maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family(familySEXP);
    Rcpp::traits::input_parameter< SEXP >::type link_func(link_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type criteria(criteriaSEXP);
    Rcpp::traits::input_parameter< double >::type loglik_reltol_cutoff(loglik_reltol_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type enet_abs_tol(enet_abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type enet_rel_tol(enet_rel_tolSEXP);
    Rcpp::traits::input_parameter< uint32_t >::type enet_max_iter(enet_max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type include_data(include_dataSEXP);
    Rcpp::traits::input_parameter< int >::type state_track_strategy(state_track_strategySEXP);
    Rcpp::traits::input_parameter< uint64_t >::type state_track_freq(state_track_freqSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_initial(theta_initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_lower_bounds(theta_lower_boundsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_upper_bounds(theta_upper_boundsSEXP);
    Rcpp::traits::input_parameter< int >::type nlopt_algorithm(nlopt_algorithmSEXP);
    Rcpp::traits::input_parameter< double >::type nlopt_xtol_rel(nlopt_xtol_relSEXP);
    Rcpp::traits::input_parameter< double >::type nlopt_ftol_rel(nlopt_ftol_relSEXP);
    Rcpp::traits::input_parameter< int >::type nlopt_maxeval(nlopt_maxevalSEXP);
    rcpp_result_gen = Rcpp::wrap(ecountgmifs_cpp(X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, include_data, state_track_strategy, state_track_freq, theta_initial, theta_lower_bounds, theta_upper_bounds, nlopt_algorithm, nlopt_xtol_rel, nlopt_ftol_rel, nlopt_maxeval));
    return rcpp_result_gen;
END_RCPP
}
// example_create_log_link
SEXP example_create_log_link();
RcppExport SEXP _ecountgmifs_example_create_log_link() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_log_link());
    return rcpp_result_gen;
END_RCPP
}
// example_create_softplus_link
SEXP example_create_softplus_link();
RcppExport SEXP _ecountgmifs_example_create_softplus_link() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_softplus_link());
    return rcpp_result_gen;
END_RCPP
}
// example_create_poisson_family
SEXP example_create_poisson_family(const double mu_min_cap, const double mu_max_cap);
RcppExport SEXP _ecountgmifs_example_create_poisson_family(SEXP mu_min_capSEXP, SEXP mu_max_capSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu_min_cap(mu_min_capSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_max_cap(mu_max_capSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_poisson_family(mu_min_cap, mu_max_cap));
    return rcpp_result_gen;
END_RCPP
}
// example_create_nb2_family
SEXP example_create_nb2_family(const double mu_min_cap, const double mu_max_cap, const double poisson_fallback_eps, const double dispersion_initial, const double dispersion_lower_bound, const double dispersion_upper_bound);
RcppExport SEXP _ecountgmifs_example_create_nb2_family(SEXP mu_min_capSEXP, SEXP mu_max_capSEXP, SEXP poisson_fallback_epsSEXP, SEXP dispersion_initialSEXP, SEXP dispersion_lower_boundSEXP, SEXP dispersion_upper_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type mu_min_cap(mu_min_capSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_max_cap(mu_max_capSEXP);
    Rcpp::traits::input_parameter< const double >::type poisson_fallback_eps(poisson_fallback_epsSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_initial(dispersion_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_lower_bound(dispersion_lower_boundSEXP);
    Rcpp::traits::input_parameter< const double >::type dispersion_upper_bound(dispersion_upper_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(example_create_nb2_family(mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound));
    return rcpp_result_gen;
END_RCPP
}
// example_create_aic_criterion
SEXP example_create_aic_criterion();
RcppExport SEXP _ecountgmifs_example_create_aic_criterion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_aic_criterion());
    return rcpp_result_gen;
END_RCPP
}
// example_create_bic_criterion
SEXP example_create_bic_criterion();
RcppExport SEXP _ecountgmifs_example_create_bic_criterion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(example_create_bic_criterion());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecountgmifs_ecountgmifs_call_context_criterion", (DL_FUNC) &_ecountgmifs_ecountgmifs_call_context_criterion, 14},
    {"_ecountgmifs_ecountgmifs_cpp", (DL_FUNC) &_ecountgmifs_ecountgmifs_cpp, 34},
    {"_ecountgmifs_example_create_log_link", (DL_FUNC) &_ecountgmifs_example_create_log_link, 0},
    {"_ecountgmifs_example_create_softplus_link", (DL_FUNC) &_ecountgmifs_example_create_softplus_link, 0},
    {"_ecountgmifs_example_create_poisson_family", (DL_FUNC) &_ecountgmifs_example_create_poisson_family, 2},
    {"_ecountgmifs_example_create_nb2_family", (DL_FUNC) &_ecountgmifs_example_create_nb2_family, 6},
    {"_ecountgmifs_example_create_aic_criterion", (DL_FUNC) &_ecountgmifs_example_create_aic_criterion, 0},
    {"_ecountgmifs_example_create_bic_criterion", (DL_FUNC) &_ecountgmifs_example_create_bic_criterion, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecountgmifs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
