# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecountgmifs_call_context_criterion <- function(criterion_ptr, negloglik = 100.0, iteration = 10L, dispersion = 0.25, epsilon = 1e-4, initialized = TRUE, n = 50.0, p = 12.0, q = 1.0, beta_value = 0.0, beta_nonzero_value = 1.0, nnz = 4L, enet_alpha = 0.75, include_data = FALSE) {
    .Call(`_ecountgmifs_ecountgmifs_call_context_criterion`, criterion_ptr, negloglik, iteration, dispersion, epsilon, initialized, n, p, q, beta_value, beta_nonzero_value, nnz, enet_alpha, include_data)
}

ecountgmifs_cpp <- function(X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, include_data, state_track_strategy, state_track_freq, theta_initial, theta_lower_bounds, theta_upper_bounds, nlopt_algorithm, nlopt_xtol_rel, nlopt_ftol_rel, nlopt_maxeval, family_link = NULL) {
    .Call(`_ecountgmifs_ecountgmifs_cpp`, X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, link_func, criteria, loglik_reltol_cutoff, enet_abs_tol, enet_rel_tol, enet_max_iter, verbose, include_data, state_track_strategy, state_track_freq, theta_initial, theta_lower_bounds, theta_upper_bounds, nlopt_algorithm, nlopt_xtol_rel, nlopt_ftol_rel, nlopt_maxeval, family_link)
}

example_create_log_link <- function() {
    .Call(`_ecountgmifs_example_create_log_link`)
}

example_create_softplus_link <- function() {
    .Call(`_ecountgmifs_example_create_softplus_link`)
}

example_create_poisson_family <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12) {
    .Call(`_ecountgmifs_example_create_poisson_family`, mu_min_cap, mu_max_cap)
}

example_create_nb2_family <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12, poisson_fallback_eps = 1e-8, dispersion_initial = 1e-4, dispersion_lower_bound = 1e-12, dispersion_upper_bound = 1e12) {
    .Call(`_ecountgmifs_example_create_nb2_family`, mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound)
}

example_create_nb2_log_family_link <- function(mu_min_cap = 1e-12, mu_max_cap = 1e12, poisson_fallback_eps = 1e-8, dispersion_initial = 1e-4, dispersion_lower_bound = 1e-12, dispersion_upper_bound = 1e12) {
    .Call(`_ecountgmifs_example_create_nb2_log_family_link`, mu_min_cap, mu_max_cap, poisson_fallback_eps, dispersion_initial, dispersion_lower_bound, dispersion_upper_bound)
}

example_create_aic_criterion <- function() {
    .Call(`_ecountgmifs_example_create_aic_criterion`)
}

example_create_bic_criterion <- function() {
    .Call(`_ecountgmifs_example_create_bic_criterion`)
}

