# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecountgmifs_call_context_criterion <- function(criterion_ptr, negloglik = 100.0, iteration = 10L, dispersion = 0.25, epsilon = 1e-4, initialized = TRUE, n = 50.0, p = 12.0, q = 1.0, beta_value = 0.0, beta_nonzero_value = 1.0, nnz = 4L, enet_alpha = 0.75, include_data = FALSE) {
    .Call(`_ecountgmifs_ecountgmifs_call_context_criterion`, criterion_ptr, negloglik, iteration, dispersion, epsilon, initialized, n, p, q, beta_value, beta_nonzero_value, nnz, enet_alpha, include_data)
}

ecountgmifs_cpp <- function(X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, linkfunc_int, nlopt_optim_reltol, loglik_reltol_cutoff, verbose = FALSE, is_fixed_disp = FALSE, fixed_disp_value = 0.0, include_data = FALSE, state_track_strategy = 0L, state_track_freq = 1L, criteria = NULL) {
    .Call(`_ecountgmifs_ecountgmifs_cpp`, X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, linkfunc_int, nlopt_optim_reltol, loglik_reltol_cutoff, verbose, is_fixed_disp, fixed_disp_value, include_data, state_track_strategy, state_track_freq, criteria)
}

