# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecountgmifs_call_score_criterion <- function(criterion, iteration = 10L, negloglik = 100.0, unpenalized_negloglik = 150.0, saturated_negloglik = 80.0, n = 50.0, p = 12.0, nnz = 3.0, df = 4.0, active_size = 3.0, dispersion = 0.25, enet_norm = 2.5, epsilon = 1e-4) {
    .Call(`_ecountgmifs_ecountgmifs_call_score_criterion`, criterion, iteration, negloglik, unpenalized_negloglik, saturated_negloglik, n, p, nnz, df, active_size, dispersion, enet_norm, epsilon)
}

ecountgmifs_cpp <- function(X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, linkfunc_int, nlopt_optim_reltol, loglik_reltol_cutoff, verbose = FALSE, is_fixed_disp = FALSE, fixed_disp_value = 0.0, state_track_strategy = 0L, state_track_freq = 1L, criteria = NULL) {
    .Call(`_ecountgmifs_ecountgmifs_cpp`, X, y, w, offset, yorig, Xtest, ytest, wtest, offsettest, weight_vec, enet_alpha, epsilon_start, epsilon_max, epsilon_min_tol, tol, iteration_max, family, linkfunc_int, nlopt_optim_reltol, loglik_reltol_cutoff, verbose, is_fixed_disp, fixed_disp_value, state_track_strategy, state_track_freq, criteria)
}

